/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nutty' at '10/18/16 10:16 PM' with Gradle 2.14.1
 *
 * @author nutty, @date 10/18/16 10:16 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
